apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: simplegrpc
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: simplegrpc
        tier: frontend
        track: stable
    spec:
      containers:
        - name: frontend
          image: "razvanincrys/frontend:latest"
          ports:
            - name: web-frontend
              containerPort: 8080