apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: simplegrpc
    tier: backend
  ports:
    - protocol: TCP
      port: 9001
      targetPort: grpc-gateway
      name: sgrpc-gateway